name: Build .NET Framework 4.8 App and Run Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Run Tests on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore ProductManagement.sln

    - name: Build solution
      run: msbuild ProductManagement.sln /p:Configuration=Release /p:OutputPath="C:\Users\teodo\source\repos\Tema2-master\bin\Debug"

    - name: Run Unit Tests
      run: |
        cd ProductManagementUnitTests
        dotnet test --configuration Release

    - name: Create ZIP of build output
      run: |
        if (-not (Test-Path "C:\deploy_directory")) {
          New-Item -ItemType Directory -Path "C:\deploy_directory"
        }
        Compress-Archive -Path C:\Users\teodo\source\repos\Tema2-master\bin\Debug\* -DestinationPath C:\deploy_directory\product.zip

    - name: Deploy Application
      run: |
        if (-not (Test-Path "C:\deploy_directory")) {
          New-Item -ItemType Directory -Path "C:\deploy_directory"
        }
        Copy-Item -Path C:\Users\teodo\source\repos\Tema2-master\bin\Debug\*.* -Destination C:\deploy_directory\ -Force