name: Build .NET Framework 4.8 App and Run Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Run Tests for ProductManagement Application
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore ProductManagement.sln

    - name: Build solution
      run: msbuild ProductManagement.sln /p:Configuration=Debug /p:OutputPath="C:\Users\teodo\source\repos\Tema2-master\bin\Debug"

    - name: Run Unit Tests
      run: |
        cd ProductManagementUnitTests
        dotnet test --configuration Release

    - name: Deploy Application
      run: |
        $deployPath = "C:\Users\teodo\deploy_directory"
        if (-not (Test-Path $deployPath)) {
          New-Item -ItemType Directory -Path $deployPath
        }
        Copy-Item -Path C:\Users\teodo\source\repos\Tema2-master\bin\Debug\*.* -Destination $deployPath -Force
        Write-Host "Fisierele copiate:"
        Get-ChildItem -Path $deployPath
        Get-ChildItem -Path $deployPath | Out-File -FilePath "$deployPath\copied_files.txt"
    
